export const themes = [
  // Light themes (alphabetically sorted)
  {
    id: 'catppuccin-latte' as const,
    name: 'Catppuccin Latte',
    description: 'Elegant light theme',
    type: 'light' as const,
    emoji: '☀️',
    icon: undefined as string | undefined, // Optional: filename in /public/theme-icons/ (e.g., 'nord.svg')
  },
  {
    id: 'kanagawa-lotus' as const,
    name: 'Kanagawa Lotus',
    description: 'Nature-inspired light theme',
    type: 'light' as const,
    emoji: '🪷',
    icon: undefined,
  },
  {
    id: 'nord-light' as const,
    name: 'Nord Light',
    description: 'Arctic, north-bluish light theme',
    type: 'light' as const,
    emoji: '☀️',
    icon: 'nord.png',
  },
  {
    id: 'rose-pine-dawn' as const,
    name: 'Rosé Pine Dawn',
    description: 'Soho vibes light theme',
    type: 'light' as const,
    emoji: '🌅',
    icon: 'rose-pine-dawn.png',
  },
  // Dark themes (alphabetically sorted)
  {
    id: 'catppuccin-mocha' as const,
    name: 'Catppuccin Mocha',
    description: 'Warm dark theme',
    type: 'dark' as const,
    emoji: '🌙',
    icon: 'catppuccin-dark.png',
  },
  {
    id: 'dracula' as const,
    name: 'Dracula',
    description: 'High contrast dark theme',
    type: 'dark' as const,
    emoji: '🧛',
    icon: undefined,
  },
  {
    id: 'everforest' as const,
    name: 'Everforest',
    description: 'Comfortable green dark theme',
    type: 'dark' as const,
    emoji: '🌲',
    icon: undefined,
  },
  {
    id: 'kanagawa-dragon' as const,
    name: 'Kanagawa Dragon',
    description: 'Darker earthy theme',
    type: 'dark' as const,
    emoji: '🐉',
    icon: undefined,
  },
  {
    id: 'kanagawa-wave' as const,
    name: 'Kanagawa Wave',
    description: 'Nature-inspired dark theme',
    type: 'dark' as const,
    emoji: '🌊',
    icon: undefined,
  },
  {
    id: 'nord' as const,
    name: 'Nord',
    description: 'Arctic, north-bluish theme',
    type: 'dark' as const,
    emoji: '❄️',
    icon: 'nord.png',
  },
  {
    id: 'one-dark' as const,
    name: 'One Dark',
    description: 'Atom inspired dark theme',
    type: 'dark' as const,
    emoji: '⚛️',
    icon: undefined,
  },
  {
    id: 'rose-pine' as const,
    name: 'Rosé Pine',
    description: 'Soho vibes dark theme',
    type: 'dark' as const,
    emoji: '🌹',
    icon: 'rose-pine.png',
  },
  {
    id: 'rose-pine-moon' as const,
    name: 'Rosé Pine Moon',
    description: 'Soho vibes darker theme',
    type: 'dark' as const,
    emoji: '🌕',
    icon: 'rose-pine-moon.png',
  },
  {
    id: 'tokyo-night' as const,
    name: 'Tokyo Night',
    description: 'Clean dark blue theme',
    type: 'dark' as const,
    emoji: '🌃',
    icon: undefined,
  },
] as const;

export type ThemeId = (typeof themes)[number]['id'];
export type Theme = (typeof themes)[number];
